App\Backoffice\Domain\User\User:
    type: entity
    table: '`user`'
    repositoryClass: App\Backoffice\Infrastructure\Persistence\UserRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    embedded:
        email:
            class: App\Backoffice\Domain\User\EmailAddress
            columnPrefix: false
        password:
            class: App\Backoffice\Domain\User\Password
            columnPrefix: false
    fields:
        roles:
            type: json
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    lifecycleCallbacks: {  }
