App\Backoffice\Domain\User\Password:
    type: embeddable
    fields:
        password:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
