version: '3.5'
services:
    app:
        build: ./docker/php/
        working_dir: /var/www
        environment:
            TIMEZONE: Europe/Kiev
            DATABASE_URL: pgsql://postgres:spacebar@database:5432/spacebar
            ENQUEUE_DSN: amqp://guest:guest@queue:5672/%2f
        volumes:
            - .:/var/www:cached
        depends_on:
            - database
        networks:
            - webnet

    composer:
        image: composer:latest
        volumes:
            - .:/var/www
        working_dir: /var/www
        depends_on:
            - app
        command: install

    web:
        image: nginx:alpine
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./public:/var/www/public:ro
        depends_on:
            - app
        ports:
            - 8090:80
        networks:
            - webnet

    database:
        image: postgres:alpine
        #volumes:
        #    - ./database:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_PASSWORD: spacebar
        networks:
            - webnet

    queue:
        image: rabbitmq:management-alpine
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - webnet

    adminer:
        image: adminer
        ports:
            - 8089:8080
        networks:
            - webnet

networks:
    webnet: