version: '3.5'
services:
    app:
        build: ./docker/php/
        working_dir: /var/www
        environment:
            TIMEZONE: Europe/Kiev
        volumes:
            - .:/var/www
        depends_on:
            - database
        networks:
            - webnet

    composer:
        image: composer:latest
        volumes:
            - .:/var/www
        working_dir: /var/www
        depends_on:
            - app
        command: install

    web:
        image: nginx:alpine
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./public:/var/www/public
        depends_on:
            - app
        ports:
            - 8000:80
        networks:
            - webnet

    database:
        image: mysql:5
        restart: always
        volumes:
            - ./database:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: spacebar
        networks:
            - webnet

networks:
    webnet: