name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.3'
          extension-csv: bcmath, intl, mbstring

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run code style checks #1
        run: composer run-script cs-check

      - name: Run code style checks #2
        run: composer run-script rector
